-- Entoo2 Database Initialization
-- This script runs on first database creation

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- For fuzzy text search

-- Create initial admin user (password: changeme123)
-- The actual password hash should be generated by the application
-- This is a placeholder that the first migration will handle

-- Grant permissions
GRANT ALL PRIVILEGES ON DATABASE entoo2 TO entoo2;

-- Create schema for better organization (optional)
-- CREATE SCHEMA IF NOT EXISTS app;

-- Log initialization
DO $$
BEGIN
    RAISE NOTICE 'Entoo2 database initialized successfully';
END $$;
